// Plain-language help for every learner-profile field, keyed by field path.
export const PROFILE_HELP: Record<string, string> = {
  schema_version: "Internal format version of this profile file. You don't need to change it.",
  id: "Short identifier used in filenames, e.g. jamie or team-onboarding. Letters, digits, dots, dashes, underscores.",
  target_learner: "Who this course is for, in a sentence. Example: 'My 12-year-old who loves Minecraft' or 'Junior analysts new to SQL'.",
  prior_education: "Formal schooling that's relevant, e.g. 'college algebra' or 'no formal CS background'.",
  prior_experience: "Hands-on experience with this subject so far, if any.",
  professional_experience: "Work background that shapes which examples will land.",
  current_skill_level: "Where the learner is starting from: beginner, intermediate, returning after a break…",
  adjacent_domains: "Subjects the learner already knows that lessons can build bridges from. One per line.",
  learning_goals: "What the learner wants to be able to do after the course. One goal per line.",
  preferred_examples: "Domains or themes examples should draw from (sports, cooking, games…). One per line.",
  examples_to_avoid: "Topics or themes to keep out of examples. One per line.",
  math_comfort: "How much math the learner is happy to see, in your own words — e.g. 'avoid equations' or 'algebra is fine'.",
  reading_level: "The reading level the course should aim for, e.g. 'middle school' or 'plain professional English'.",
  pace: "How quickly to move through material, e.g. 'slow and thorough' or 'brisk with recaps'.",
  desired_depth: "How deep to go: quick overview, working knowledge, or expert detail.",
  time_budget: "Total time the learner can give the course, e.g. '30 minutes a day for two weeks'.",
  assessment_styles: "How the learner likes to be tested (quizzes, projects, flashcards…). One per line.",
  accessibility_constraints: "Anything the course must accommodate — dyslexia-friendly text, screen-reader use, no audio… One per line.",
  tone_preference: "The voice the course should use, e.g. 'encouraging', 'straight to the point', or 'playful'.",
  sensitive_areas: "Subjects to handle carefully or skip entirely. One per line.",
  "learning_preferences.preferred_modalities": "How the learner best absorbs material: reading, diagrams, worked examples, practice problems… One per line.",
  "learning_preferences.explanation_style": "How explanations should be built, e.g. 'intuition first, then formalism'.",
  "learning_preferences.preferred_visual_aids": "Kinds of visuals that help: flowcharts, tables, timelines… One per line.",
  "learning_preferences.diagram_frequency": "How often to include diagrams, e.g. 'every concept' or 'only when essential'.",
  "learning_preferences.interaction_style": "How interactive lessons should feel, e.g. 'frequent check-ins' or 'read straight through'.",
  "learning_preferences.practice_style": "The kinds of practice that work: drills, open-ended projects, spaced review… One per line.",
  "learning_preferences.feedback_style": "How feedback should sound, e.g. 'gentle and specific' or 'direct'.",
  "learning_preferences.worked_example_preference": "How much worked examples should carry the teaching, e.g. 'show one before every exercise'.",
  "learning_preferences.common_sticking_points": "Where this learner tends to get stuck, so the course slows down there. One per line.",
  "learning_preferences.attention_constraints": "Focus limits to design around — short sessions, minimal walls of text… One per line.",
  "learning_preferences.review_style": "How the course should reinforce earlier material: summaries, spaced repetition, cumulative quizzes… One per line.",
  "localization.jurisdiction": "Country or region whose laws and conventions examples should follow, e.g. 'US' or 'Germany'.",
  "localization.locale": "Language/region code for the course text, e.g. 'en-US'.",
  "localization.units": "Measurement system for examples: metric or imperial.",
  "localization.language_register": "How formal the language should be, e.g. 'casual' or 'formal'.",
  "privacy.private_by_default": "When on, profile details stay out of anything you publish unless explicitly marked publishable.",
  "privacy.include_in_published_output": "When on, the publishable summary below is included in exported courses.",
  "privacy.publishable_summary": "A short learner description that is safe to publish with the course, if you choose to include it.",
  "metadata.*": "Extra structured notes stored with the profile for your own reference. Not included in model prompts today.",
};
