"""Public package for local-first education guide generation."""

from education_pipeline.config import (
    DEFAULT_STAGE_RECOMMENDATIONS,
    STAGE_ORDER,
    ConfigError,
    ModelCatalog,
    ModelOption,
    ModelPlan,
    Provider,
    StageModelPlan,
    load_model_catalog,
    load_model_plan,
    parse_model_catalog,
    parse_model_plan,
)
from education_pipeline.prompts import (
    PromptArtifact,
    SpecPromptInput,
    compile_attached_spec_prompt,
    compile_spec_prompt,
)
from education_pipeline.runs import (
    MANIFEST_SCHEMA_VERSION,
    RUN_SUBDIRS,
    SUPPORTED_STAGES,
    PromptFile,
    RunStore,
    StagePaths,
)
from education_pipeline.profiles import (
    PROFILE_SCHEMA_VERSION,
    LearnerLocalization,
    LearnerPreferences,
    LearnerPrivacy,
    LearnerProfile,
    load_learner_profile,
    parse_learner_profile,
    render_profile_prompt_context,
    render_profile_public_summary,
)
from education_pipeline.workspace import ProfileAttachment, ProfileStore

__all__ = [
    "DEFAULT_STAGE_RECOMMENDATIONS",
    "MANIFEST_SCHEMA_VERSION",
    "PROFILE_SCHEMA_VERSION",
    "RUN_SUBDIRS",
    "STAGE_ORDER",
    "SUPPORTED_STAGES",
    "ConfigError",
    "LearnerLocalization",
    "LearnerPreferences",
    "LearnerPrivacy",
    "LearnerProfile",
    "ModelCatalog",
    "ModelOption",
    "ModelPlan",
    "PromptArtifact",
    "PromptFile",
    "ProfileAttachment",
    "ProfileStore",
    "Provider",
    "RunStore",
    "SpecPromptInput",
    "StageModelPlan",
    "StagePaths",
    "compile_attached_spec_prompt",
    "compile_spec_prompt",
    "load_learner_profile",
    "load_model_catalog",
    "load_model_plan",
    "parse_learner_profile",
    "parse_model_catalog",
    "parse_model_plan",
    "render_profile_prompt_context",
    "render_profile_public_summary",
]
